### ISSUE TITLE
Rename from Shipyard to Jumppad

### ISSUE THREAD

**Issue by zcubbs** [jumppad-labs/jumppad#211]
Hello @nicholasjackson,
A bit late to the party... I can't seem to find the thread/post about the switch from Shipyard to Jumppad. Any way i could get some context for the change ?

Cheers.

**Comment by nicholasjackson** [comment]
Hi @zcubbs, we posted something up in the discord channel but have not yet added anything to the website and ReadMe. Over the last few months we have been working on a new parser for the configuration that brings huge upgrades to the way that you define resources.

For example, in the old system you could do something like this to create a templated config file and use it from a container.

```hcl
template "consul_config" {

  source = <<-EOF
    data_dir = "#{{ .Vars.data_dir }}"
  EOF

  destination = "./consul_config/consul.hcl"

  vars = {
    data_dir = "/tmp"
  }
}

container "consul" {
  depends_on = ["template.consul_config"]

  command = ["consul", "agent", "-config-file=/config/consul.hcl"]

  volume {
    source      = "./consul_config"
    destination = "/config"
  }
}
```

With the new syntax this can be rewritten removing the depends_on as all properties are now reference-able, whenever you reference a property of another resource, jumppad automatically creates a dependency.

```hcl
resource "template" "consul_config" {

  source = <<-EOF
    data_dir = "#{{ .Vars.data_dir }}"
  EOF

  destination = "./consul_config/consul.hcl"

  variables = {
    data_dir = "/tmp"
  }
}

resource "container" "consul" {
  command = ["consul", "agent", "-config-file=/config/consul.hcl"]

  volume {
    source      = resource.template.consul_config.destination
    destination = "/config/config.hcl"
  }
}
``` 

This in our humble opinion is a huge improvement but also a very big breaking change to the current configuration.

We have also dramatically improved modules, all resources in modules are now module scoped, this means that no longer do modules have to contain unique references. You can use a module more than once in the same configuration. Variables for modules are now module scoped rather than globally scoped giving a vastly improved experience. For example, you can now do something like this.

```hcl
resource "network" "local" {
  subnet = "10.5.0.0/16"
}

resource "k8s_cluster" "k3s" {
  driver = "k3s" // default

  nodes = 1 // default

  network {
    id = resource.network.local.id
  }
}

module "vault1" {
  source = "github.com/jumppad-labs/blueprints/modules//vault"

  variables = {
    namespace      = "one"
    helm_version   = "0.24.0"
    api_port       = 8200
    k8s_cluster_id = resource.k8s_cluster.k3s.id
  }
}

module "vault2" {
  source = "github.com/jumppad-labs/blueprints/modules//vault"

  variables = {
    namespace      = "two"
    helm_version   = "0.24.0"
    api_port       = 8200
    k8s_cluster_id = resource.k8s_cluster.k3s.id
  }
}

output "VAULT_ADDR_1" {
  value = module.vault1.output.vault_addr
}

output "VAULT_ADDR_2" {
  value = module.vault2.output.vault_addr
}

output "KUBECONFIG" {
  value = resource.k8s_cluster.k3s.kubeconfig
}
```

This is a huge upgrade on the previous way of working and off and is something we always wanted to do when starting the project, but, processing HCL with go-hcl does not give this capability. We had to write a higher level parser that uses go-hcl, something that was quite a bit of work. The impact of the new parser also meant that the core Shipyard code needed quite a few changes, something that is still ongoing, but, right now is stable.

So to your question, "Why rename Shipyard to Jumppad?", there are some amazing things we want to do with Shipyard this year, creating an easy to use module registry, enabling easy connections between blueprints, and more. 

Since there is already a similarly named project (not getting into who claimed Shipyard first, it was actually neither of us, it was Docker), and the new version would introduce so many breaking changes, we felt that this was also the right time to rename the project, give it a unique identity, and relaunch it. It will probably take a few more weeks to get the docs and other elements finalised but things are pretty good right now. No acquisitions, the project is still staying OSS, we just wanted a unique identity. 

We hope you really like the new features,  we have been using Jumppad as my daily driver for a couple of weeks to try get the bugs out. In my humble opinion, the way that Jumppad now works is the way that we always wanted it to work when we started the project a few years ago.

**Comment by zcubbs** [comment]
Thank you for the detailed explanation.
